#ifndef _PLAT_TIMER_H_
#define _PLAT_TIMER_H_

#include "config.h"

extern void plat_init_timer(void);

#define TIMER_FREQ (1000000ul)
#define TIMER_CLOCK_PRESCALER (fMSCLK / TIMER_FREQ)

#if ((TIMER_FREQ > fMSCLK))
#error "TIMER_FREQ > fMSCLK"
#endif

#if ((TIMER_CLOCK_PRESCALER * TIMER_FREQ) != fMSCLK)
	#warning "TIMER_FREQ is not a devider of fMCLK!"
#endif

#if ((TIMER_CLOCK_PRESCALER) == 1)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_1
#endif
#if ((TIMER_CLOCK_PRESCALER) == 2)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_2
#endif
#if ((TIMER_CLOCK_PRESCALER) == 3)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_3
#endif
#if ((TIMER_CLOCK_PRESCALER) == 4)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_4
#endif
#if ((TIMER_CLOCK_PRESCALER) == 5)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_5
#endif
#if ((TIMER_CLOCK_PRESCALER) == 6)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_6
#endif
#if ((TIMER_CLOCK_PRESCALER) == 7)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_7
#endif
#if ((TIMER_CLOCK_PRESCALER) == 8)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_8
#endif
#if ((TIMER_CLOCK_PRESCALER) == 9)
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is set to 8"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_8
#endif
#if ((TIMER_CLOCK_PRESCALER) == 10)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_10
#endif
#if ((TIMER_CLOCK_PRESCALER) == 11)
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is set to 10"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_10
#endif
#if ((TIMER_CLOCK_PRESCALER) == 12)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_12
#endif
#if ((TIMER_CLOCK_PRESCALER) == 13)
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is set to 12"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_12
#endif
#if ((TIMER_CLOCK_PRESCALER) == 14)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_14
#endif
#if ((TIMER_CLOCK_PRESCALER) == 15)
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is set to 14"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_14
#endif
#if ((TIMER_CLOCK_PRESCALER) == 16)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_16
#endif
#if ((TIMER_CLOCK_PRESCALER) >= 17 && (TIMER_CLOCK_PRESCALER) <= 19)
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is set to 17"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_16
#endif
#if ((TIMER_CLOCK_PRESCALER) == 20)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_20
#endif
#if ((TIMER_CLOCK_PRESCALER) >= 21 && (TIMER_CLOCK_PRESCALER) <= 23)
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is set to 20"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_20
#endif
#if ((TIMER_CLOCK_PRESCALER) == 24)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_24
#endif
#if ((TIMER_CLOCK_PRESCALER) >= 25 && (TIMER_CLOCK_PRESCALER) <= 27)
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is set to 24"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_24
#endif
#if ((TIMER_CLOCK_PRESCALER) == 28)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_28
#endif
#if ((TIMER_CLOCK_PRESCALER) >= 29 && (TIMER_CLOCK_PRESCALER) <= 31)
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is set to 28"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_28
#endif
#if ((TIMER_CLOCK_PRESCALER) == 8)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_32
#endif
#if ((TIMER_CLOCK_PRESCALER) >= 33 && (TIMER_CLOCK_PRESCALER) <= 39)
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is set to 32"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_32
#endif
#if ((TIMER_CLOCK_PRESCALER) == 40)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_40
#endif
#if ((TIMER_CLOCK_PRESCALER) >= 41 && (TIMER_CLOCK_PRESCALER) <= 47)
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is set to 40"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_40
#endif
#if ((TIMER_CLOCK_PRESCALER) == 48)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_48
#endif
#if ((TIMER_CLOCK_PRESCALER) >= 49 && (TIMER_CLOCK_PRESCALER) <= 55)
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is set to 48"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_48
#endif
#if ((TIMER_CLOCK_PRESCALER) == 56)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_56
#endif
#if ((TIMER_CLOCK_PRESCALER) >= 57 && (TIMER_CLOCK_PRESCALER) <= 63)
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is set to 17"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_56
#endif
#if ((TIMER_CLOCK_PRESCALER) == 64)
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_64
#endif
#if ((TIMER_CLOCK_PRESCALER) > 64 )
  #warning "TIMER_A_CLOCKSOURCE_DIVIDER is > 64"
  #define TIMER_A_CLOCKSOURCE_DIVIDER TIMER_A_CLOCKSOURCE_DIVIDER_64
#endif

#endif
